# src/Stsbl/IPv6Bundle/Resources/config/services.yml
services:
    stsbl.ipv6.util.network:
        class: Stsbl\IPv6Bundle\Util\Network6
        arguments: ["@iserv.shell", "@iserv.host_manager"]

    stsbl.ipv6.idesk:
        class: Stsbl\IPv6Bundle\EventListener\IDeskListener
        arguments: ["@doctrine", "@iserv.config", "@request_stack", "@stsbl.ipv6.util.network", "@iserv.shell"]
        calls:
          - ["setContainer", ["@service_container"]]
        tags:
          - { name: kernel.event_listener, event: iserv_portal.build_idesk, method: onBuildIDesk }
