# src/Stsbl/IPv6Bundle/Resources/config/services.yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        IServ\CoreBundle\EventListener\IDeskListenerInterface:
            tags:
                - { name: kernel.event_listener, event: iserv_portal.build_idesk, method: onBuildIDesk }

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - [setContainer]

        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            tags:
                - { name: kernel.event_subscriber }


    Stsbl\IPv6Bundle\:
        resource: '../../{Controller,EventListener,Util}'
        bind:
            $resolver: '@controller_resolver'
            # FIXME can be removed after proper fix for file-distribution!
            $hostManager: '@iserv.host_manager'
