# src/Stsbl/IPv6Bundle/Resources/config/services.yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Stsbl\IPv6Bundle\:
        resource: '../../'
        exclude: '../../{Entity,Tests,Resources}'
